import os

from dotenv import load_dotenv

load_dotenv(override=True)

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')
ZHIPU_API_KEY = os.getenv('ZHIPU_API_KEY')
MINIMAX_API_KEY = os.getenv('MINIMAX_API_KEY')
MINIMAX_BASE_URL = os.getenv('MINIMAX_BASE_URL')
ALIBABA_API_KEY = os.getenv('ALIBABA_API_KEY')
ALIBABA_BASE_URL = os.getenv('ALIBABA_BASE_URL')
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL')
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL')


QWEN_EMBEDDING_BASE_URL = os.getenv('QWEN_EMBEDDING_BASE_URL')
QWEN_EMBEDDING_MODEL_NAME = os.getenv('QWEN_EMBEDDING_MODEL_NAME')

MILVUS_URI =os.getenv('MILVUS_URI')
MILVUS_USER = os.getenv('MILVUS_USER')
MILVUS_PASSWORD = os.getenv('MILVUS_PASSWORD')
MILVUS_COLLECTION_NAME = os.getenv('MILVUS_COLLECTION_NAME')
MILVUS_DATABASE_NAME = os.getenv('MILVUS_DATABASE_NAME')
NO_PROXY_IP =os.getenv('NO_PROXY_IP')

LOCAL_BASE_URL = 'http://10.191.160.91:8020/v1'